config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :reviews
  resources :movies, only: [:index, :new, :create, :show]
  resources :users

  get '/', to:'static#index'

  post '/', to:'sessions#create'

  get '/logout', to:'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews
    has_many :reviewers, through: :reviews, source: :user
    validates :title, uniqueness: {scope: :year, message: "This film already exists"}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :movies, through: :reviews
  has_secure_password
  validates_uniqueness_of :name, message: "User already exists"
  validates_presence_of :name, :password, message: "can't be blank"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
    end

    def new
        if !helpers.logged_in?
            redirect_to "/"
        elsif params[:title]
            @movies = []
            search_movies(params[:title]).each do |movie_hash|
                movie = new_movie(movie_hash)
                @movies << movie
            end
        end
    end
    
    
    def create
        @movie = new_movie(find_movie(params[:title]))
        if @movie.save
            redirect_to movie_path(@movie)
        elsif Movie.find_by(title: params[:title])
            @movie = Movie.find_by(title: params[:title])
            redirect_to movie_path(@movie)
        else
            redirect_to user_path(helpers.current_user)
        end
    end

    def show
        @movie = Movie.find(params[:id])
    end

    private

    def movie_params

    end

    def search_movies(movie_title)
        request = RestClient.get "http://www.omdbapi.com/?apikey=c01df668&s=#{movie_title}&plot=full"
        api_hash = JSON.parse(request.body)
        search_results = api_hash["Search"]
    end

    def new_movie(api_hash)
        attributes = {}
        attributes[:title] = api_hash["Title"]
        attributes[:year] = api_hash["Year"]
        attributes[:rating] = api_hash["Rated"]
        attributes[:release_date] = api_hash["Released"]
        attributes[:runtime] = api_hash["Runtime"]
        attributes[:genre] = api_hash["Genre"]
        attributes[:plot] = api_hash["Plot"]
        attributes[:awards] = api_hash["Awards"]
        attributes[:poster_url] = api_hash["Poster"]
        Movie.new(attributes)
    end

    def find_movie(movie_title)
        request = RestClient.get "http://www.omdbapi.com/?apikey=c01df668&t=#{movie_title}&plot=full"
        api_hash = JSON.parse(request.body)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @review = Review.new
        @movie = Movie.find(params[:movie_id])
    end
    
    def create
        @review = Review.new(review_params)
        @review.movie = Movie.find(params[:review][:movie_id])
        @review.user = User.find(params[:review][:user_id])
        if @review.save
            redirect_to user_path(helpers.current_user)
        else
            redirect_to movie_path(@review.movie)
        end
    end
    
    private
    
    def review_params
        params.require(:review).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
        @user = User.find_by(name: params[:name])

        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to new_user_path
        end
    end

    def destroy
        session.clear
        redirect_to "/"
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      if !helpers.logged_in?
        redirect_to "/"
      end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          flash[:success] = "User successfully created"
          session[:user_id] = @user.id
          redirect_to @user
        else
          flash[:error] = "Something went wrong"
          redirect_to 'new'
        end
    end
    
    def show
      if !helpers.logged_in?
        redirect_to "/"
      end
        @user = helpers.current_user
    end

    private
  
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if !!session[:user_id]
    end
    
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash-alerts"><%= flash[:alert] %></div>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<% @movies.sort_by(&:title).each do |movie| %>
    <div>
        <%= link_to movie.title, movie %>
    </div>
<% end %>

app/views/movies/new.html.erb
<h1> Submit a New Movie </h1>

<% if @movies %>
    Select the correct movie
    <% @movies.each do |movie| %>
        <div>
            <b><%= movie.title %> - <%= movie.year %></b> 
            <%= button_to "Select", movies_path, params: {title: movie.title} %> <br>
            
            <img src="<%= movie.poster_url%>" alt="<%= movie.title %> poster">
        </div>
    <% end %>
<% else %>
    <%= form_with model: @movie, url: new_movie_path, method: "get" do |f|%>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title%>
    </div>
    <%= f.submit %>
<% end %>
<% end %>

app/views/movies/show.html.erb
<h1> <%= @movie.title %> - <%=@movie.year%> </h1>

<%= button_to "Review", new_review_path, method: "get", params: {movie_id: @movie.id} %>
<img src="<%=@movie.poster_url%>" alt="<%=@movie.title%>-poster">
<p>Rated: <%=@movie.rating%></p>
<p>Release Date: <%=@movie.release_date%></p>
<p>Runtime: <%=@movie.runtime%></p>
<p>Genre: <%=@movie.genre%></p>
<p>Plot: <%=@movie.plot%></p>
<p>Awards: <%=@movie.awards%></p>

<h3>Reviews:</h3>
<% @movie.reviews.each do |review| %>
    <i><%= review.content %></i> <br>
    -<%= link_to review.user.name, user_path(review.user) %>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<img src="<%=@movie.poster_url%>" alt="<%=@movie.title%> poster">
<h3>Write your review for <%= @movie.title %>:</h3>
<%= form_with model: @review do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :movie_id, value: @movie.id %>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>
    <br>
    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome, <%=@user.name%> </h1>

<div>
<h3>Reviewed Movies</h3>
<% @user.movies.each do |movie| %>
    <div><%= link_to movie.title, movie %></div>
<% end %>
</div>

<div>
<h3>Review a movie</h3>
<%= form_with model: @movie, url: new_movie_path, method: "get" do |f|%>
    <div>
        <%= f.label :title %>
        <input list="movies" name="title" id="title">
        <datalist id="movies">
            <%= Movie.all.each do |movie| %>
                <option value = "<%= movie.title %>">
            <% end %>
        </datalist>
    </div>
    <%= f.submit "Find Movie" %>
<% end %>
</div>